### ISSUE TITLE
support for VM with two disks (e.g. SCSI and EFI)

### ISSUE THREAD

**Issue by ak2k** [ossobv/proxmove#31]
Thank you for this utility!

I noticed that when moving a VM that had a mounted SCSI disk as well as an EFI disk, the EFI disk was left behind.

I may have misconfigured something, or it may have been that UEFI isn't supported, but I wanted to mention in case it was an unexpected edge case that you would value hearing about.

**Comment by wdoekes** [comment]
Thank you for the report.

That behaviour is not intentional. Without digging into this deeply, I wouldn't know how/why and EFI disk would exist. It's all SCSI/VirtIO right? One large disk and one small one. I don't see why PVE/proxmove would care _what_ is on it.

If you can reproduce and show the (sanitized) `--debug` output, maybe the problem is easy to spot/fix.

**Comment by ak2k** [comment]
My pleasure!

As far as I understand, the UEFI disk is needed if you are running the OVMF/UEFI bios type (instead of SeaBios). I did this because documentation suggested it to be necessary for PCI passthrough.
<img width="611" alt="Screen Shot 2021-02-08 at 1 00 35 PM" src="https://user-images.githubusercontent.com/19240940/107262630-c7da7000-6a0e-11eb-9801-d2ffb9e1f0ca.png">

Regrettably I no longer have the debug output, but I do recall that it didn't appear in any of the discovered/reported disks as though it was not seen by the utility. I could always create a new OVMF VM with an associated UEFI disk in Proxmox, as I expect this to be perfectly reproducible, but I wonder if it would be necessary for you to have it locally for you to try to understand the API command necessary for proxmox to report that device so that you could flag it for transfer.

In the proxmox host config, the line is, "efidisk0: local-zfs:vm-101-disk-1,size=1M".

**Comment by wdoekes** [comment]
> `efidisk0: local-zfs:vm-101-disk-1,size=1M`

That's useful info indeed.

In that case it should be a matter of adding 'efidisk' to https://github.com/ossobv/proxmove/blob/master/proxmove#L49.

**Comment by wdoekes** [comment]
Ok. That would be a separate issue then, caused by: https://github.com/ossobv/proxmove/blob/18fcd8dfed316c70341255c0c3166a8229ac3b85/proxmove#L1860-L1876

You could disable that by adding `and False` here:
https://github.com/ossobv/proxmove/blob/18fcd8dfed316c70341255c0c3166a8229ac3b85/proxmove#L1867

For a better fix, the volume type would need to be available in the translator so it can skip setting discard=on if it sees type `efidisk`.
